### ISSUE TITLE
encode the fields __typename as part of the inserted object

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/woo.sh#100]
This ticket is about addressing the current dependency of the resolver functions on the object ID for accessing the object type name. Inline fragments (whether used for interfaces or unions) depend on the method `__resolveType` to get the underlying object type. For example, we currently do:
```javascript
    SomeInterface: {
        __resolveType: (parent, args, context, info) =>
            return parent._id.split('/')[0]
    }
```
However, if we instead assume that the `__typename` field is actually stored as part of the document then we would return this field immediately, regardless of the ID format:
```javascript
    SomeInterface: {
        __resolveType: (parent, args, context, info) =>
            return parent.__typename
    }
```
This also means that we need to update `create` and `createEdge` to include this new field.

**Comment by epii-1** [comment]
I knew I had seen `__typename` somewhere! https://graphql.org/learn/queries/#meta-fields

Is this not reachable at the resolver level? And we hence don't have to actually store it ourselves in the db.
Or do we only have access to later, and then can't use it in the resolver as we require?
