### ISSUE TITLE
Annotating edges in mutations

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/woo.sh#24]
We need a strategy to deal with annotations on fields during mutations. This is supported in the spec with regard to types for edges and their corresponding operations. However, the use of arguments on input type fields is not supported in GraphQL, and if an object has an edge annotation marked as required/non-null, it can currently not be created.

There are a couple of alternatives for this as I see it (naming may vary). Assume the following incomplete schema:

```graphql
type Person {
   id: ID!
   name: String!
   knows(since: Date!, description: String): [Person]
}

mutation {
   createPerson(data: _InputToCreatePerson)
}

input _InputToCreatePerson {
   name: String!
   knows: [_InputToConnectKnowsOfPerson]
}
``` 

1. We could provide additional fields for the annotations in `_InputToConnectX`, e.g.:

```graphql
input _InputToConnectKnowsOfPerson {
   connect: ID
   create: _InputToCreatePerson
   since: Date!
   description: String
}
```

2. Another alternative would be to define a new type that defines fields for annotations on the edge, e.g.:
```graphql
input _InputToConnectKnowsOfPerson {
   connect: ID
   create: _InputToCreatePerson
   annotation: _InputToAnnotateKnowsOfPerson! # when should this field be marked as non-null?
}

input _InputToAnnotateKnowsOfPerson {
   since: Date!
   description: Date
}
```

The benefit of using alt 1 is that we don't have to add any additional input types, but simply extend the current `_InputToConnectX`. This is also close to the pattern for `_InputToCreateXEdgeFromY` in the spec. The benefit of using alt 2 is that the field names for all `_InputToConnectX` input types are fixed (similar to providing a single input type as data during mutations). If we go with alternative 2, we may also consider using it for the `_InputToCreateXEdgeFromY`, e.g.

```graphql
input _InputToCreateKnowsEdgeFromPerson {
   sourceID: ID!
   targetID: ID!
   annotations: _InputToAnnotateKnowsOfPerson! # when should this field be marked as non-null?
}
```

@hartig

**Comment by hartig** [comment]
Just to see what each of the two alternatives would look like from the perspective of the users, I am writing example mutation operations here:

Assuming alternative 1, the user would have to write something like the following.
```graphql
createPerson(
   data: {
      name: "Alice"
      knows: [
         {
            connect: 261
            since: "02-02-2016"
            description: "abcdef"
         }
      ]
   }
) {
   id
   name
}
```

Assuming alternative 2, the user would have to write something like the following.
```graphql
createPerson(
   data: {
      name: "Alice"
      knows: [
         {
            connect: 261
            annotations: {
               since: "02-02-2016"
               description: "abcdef"
            }
         }
      ]
   }
) {
   id
   name
}
```

**Comment by hartig** [comment]
Alternative 2 looks cleaner. Let's go with that one.

Then, as you say, we should adapt the `_InputToCreateXEdgeFromY` types accordingly. I will edit the wiki.

**Comment by hartig** [comment]
I have updated the wiki -- see: https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#54-creating-an-edge

One thing though regarding naming conventions: In your example, the input type for the annotation object is named `_InputToAnnotateKnowsOfPerson`. To be consistent with the naming scheme for creating and for updating edges (Sections 5.4 and 5.5 in the aforementioned wiki page), I propose to name it `_InputToAnnotateKnowsEdgeFromPerson`.

**Comment by hartig** [comment]
Another thing, which is unrelated to the actual issue but related to your first code example: Notice that this piece of schema mixes parts from the DB schema and parts from the generated API schema.

That is, while the mutation type and the input type is part of the generated API schema, the following line is DB schema:
```graphql
     knows(since: Date!, description: String): [Person]
```
More precisely, the argument definitions in this field definition may occur only in the DB schema, but they should be removed when generating the API schema.

**Comment by keski** [comment]
Thanks for clarifying this. I assume that this means that before having the edge objects in place we will not be able to filter on any of the annotations of edges?

**Comment by hartig** [comment]
> I assume that this means that before having the edge objects in place, we will not be able to filter on any of the annotations of edges?

Again, this is unrelated to the current issue. However, since you ask: It would be possible to add a second filter argument into the field definitions that correspond to edges (such as the `knows` field in the examples above). That is, there would be one filter argument that allows users to filter the resulting list by conditions on the objects the list should contain (which is what we currently have with the `filter` arguments), and the new second filter argument (which would need to be named differently) would allow users to to filter the resulting list by conditions on the edges that lead to the objects in the list. Perhaps this gets to confusing for users. Therefore, I propose to ignore this option. Instead, filtering based on edge annotations should be added only to the generated fields that allow users to traverse to edge objects (as described in [Sect.4 of the approach](https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#4-additional-fields-and-types-for-edges)).

**Comment by hartig** [comment]
#31 and #32 are related issues.
#31 is about enabling users to request the edge properties created/updated based on the feature to be added by this issue.
#32 is about enabling users to filter based on these edge properties.

**Comment by hartig** [comment]
@rcapshaw please check to which extend it is already possible now to specify edge properties. It needs to be possible both i) in edge-creation operations and ii) when creating an edge inline (i.e., within other creation operations). Please first document here the findings of checking and, then, start implementing the missing parts.

**Comment by hartig** [comment]
The corresponding gitlab issue was 16.

**Comment by epii-1** [comment]
Things missing so far seems to be:
Adding annotations to `_InputToConnectXOfY`,
handling annotations in `create`,
handling annotations in `update`.

Annotation fields exists for edge-types. They can be given values when creating edges directly, but not when adding edges indirectly from `createObject`-mutations.

**Comment by epii-1** [comment]
With #66 being merged and this being reflected in the changelog, this issue is now implemented.
