### ISSUE TITLE
add fields and types to request edge properties

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/woo.sh#31]
The fourth step of the approach should be supported. See: https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#4-additional-fields-and-types-for-edges

**Comment by hartig** [comment]
#24 is related to this issue in the sense that #24 is about enabling users to create and to update the edge properties that can be queried based on the feature to be added by this issue

**Comment by epii-1** [comment]
With #80 this should now be implemented and the issue can be closed.

**Comment by hartig** [comment]
Sounds good. I am closing the issue then.
