### ISSUE TITLE
support filtering lists of edges based on edge properties

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/woo.sh#32]
Once #31 has been addressed, the tool should be extended to also support filtering when retrieving lists of edges.

For instance, consider the example in [the corresponding part of the description of the approach](https://github.com/LiUGraphQL/pgschema-to-apischema/wiki/Overview-of-the-Approach#4-additional-fields-and-types-for-edges). Once #31 has been addressed, we can write the following query.
```graphql
query {
    Blogger(id:3991) {
        name
        _outgoingBlogsEdges {
            certainty
            target {
                title
                text
            }
        }
    }
}
```

The purpose of this issue here is to extend the approach such that we may extend the example query as follows. 
```graphql
query {
    Blogger(id:3991) {
        name
        _outgoingBlogsEdges( filter: {certainty:{ _gte: 0.4 }} ) {
            certainty
            target {
                title
                text
            }
        }
    }
}
```
The schema for this new filter feature should resemble the schema for the existing filter features.

**Comment by epii-1** [comment]
With @keski pushing 52585c8 manually, this should now be implemented.
