### ISSUE TITLE
listOf queries not generated for interfaces

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/woo.sh#51]
`listOfX` query operations are generated for both types and interfaces in the API generator. However, in the template used by the resolver-generator this is missing for interfaces. This means that e.g. `listOfJobs` will always return `none`. The underlying code already supports interfaces for `listOfX` queries (including filters). This is therefore a minor bug that is easily fixed by including the following in the resolver template:
```
    % for interface_name in data['interfaces']:
        listOf${interface_name}s: async (parent, args, context, info) => await tools.getList(args, info),
    % endfor
```

**Comment by keski** [comment]
Resolved following https://github.com/LiUGraphQL/woo.sh/pull/46
