### ISSUE TITLE
Bug in API schema generator related to the uniqueForTarget constraint

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/woo.sh#55]
The unique-for-target constraints that can be specified by adding the `@uniqueForTarget` directive is not correctly captured when generating the API schema.

As an example, consider the following part of a DB schema:
```graphql
type Blogger {
  blogs: [Blog]  @uniqueForTarget
}

type Blog {
  text: String!  @required
}
```
The directive `@uniqueForTarget` in this example says that every `Blog` node can have at most one incoming `blogs` edge from some `Blogger`. Consequently, when we create the corresponding API schema and add a field to `Blog` that can be used to traverse these edges in the reverse direction, we expect this added field to be of type `Blogger` and not `[Blogger]` (list of `Blogger` objects). In other words, we expect the API schema to look as follows.
```graphql
type Blogger {
  blogs: [Blog]
}

type Blog {
  text: String!
  _blogsFromBlogger: Blogger
}
```
However, in contrast to this expected API schema, our generator currently produces the following.

```graphql
type Blogger {
  blogs: [Blog]
}

type Blog {
  text: String!
  _blogsFromBlogger(filter: _FilterForBlogger): [Blogger]
}
```
This issue needs to be fixed.

**Comment by keski** [comment]
Resolved following merge of #54
