### ISSUE TITLE
creationDate and lastUpdateDate is not enforced/kept properly for edges

### ISSUE THREAD

**Issue by epii-1** [LiUGraphQL/woo.sh#63]
Currently `creationDate` for edges is only enforced when the edge is created from `createEdge` not when the edge is created by `create`-object calls (quite easy to fix).
What is more complicated to fix is the `lastUpdateDate`. As we currently recreate edges on an `update`-object call (if we update those edges at all), we would then get new `creationDate`s for those edges if fixed in similar fashion as to when creating objects.
This needs to be changed if `creationDate` and `lastUpdateDate` are to behave as expected when used for queried etc..
One alternative would be to prevent edge updates from object updates, and only allow edges to be updated from actual edge update calls, which is currently not implemented.

@hartig @keski @rcapshaw

**Comment by hartig** [comment]
Leif, good point! Yes, these dates-related fields should not simply be ignored (and even left out) for edges that are created or updated inline within create-object or update-object operations.

As you say, the `creationDate` should be easy.

...and the `lastUpdateDate` is tricky. However, we can also take the following position: If a user updates the (outgoing) edges of a node via an update-object operation, then this is really like replacing all the existing edges with new ones, even if some of the replacing edges are equivalent to some of the replaced edges. Taking this position will simplify matters because we do not have to trouble ourselves with a need to keep edges and update their `lastUpdateDate` field (of course, the update-edge operations are a different matter).

Sounds good?

**Comment by epii-1** [comment]
@hartig , 
> ...and the lastUpdateDate is tricky. However, we can also take the following position: If a user updates the (outgoing) edges of a node via an update-object operation, then this is really like replacing all the existing edges with new ones, even if some of the replacing edges are equivalent to some of the replaced edges. Taking this position will simplify matters because we do not have to trouble ourselves with a need to keep edges and update their lastUpdateDate field (of course, the update-edge operations are a different matter).

This is how it's done now (or technically after the correction of PR#66).

I must however question this approach as it allows the deletion of edges indirectly, which might not be desired. We could instead modify `update` to only allow the addition of new edges, and force all other edge modifications to be done through `updateEdge` and/or `deleteEdge` calls. This approach also raises the question if `updateEdge` should be able to change the source/target of an edge (and hence, modify the data of the source/target). Or might an `redirectEdge` function and corresponding api-call be relevant?

Either option has it's pros and cons.

**Comment by hartig** [comment]
I think you are right. The more I ponder on it, the more I think that we should actually disallow (and, in fact, take away) the option to update a node's (outgoing) edges via an update-object operation. This option has always been a huge source of misunderstanding and confusion. I will create a separate issue to discuss this question further and, ultimately, to plan the removal of this option.

To your other point ("the question if updateEdge should be able to change the source/target of an edge"), I would say no! Updates of edges should be concerned only with the annotations but not with moving edges around in the graph (i.e., changing what their head or their tail is). The latter would just open another can of worms and I don't see any clear use cases that justify putting effort into this now. Should we have a use case later, I would probably prefer your idea of adding a completely separate kind of operation (redirectEdge or moveEdge or something), but for the moment, let's simply ignore this.

**Comment by hartig** [comment]
@epii-1 now that we have decided to eventually remove the option to update a node's (outgoing) edges via an update-object operation (see #67), is there anything else left to do regarding this issue here?

**Comment by epii-1** [comment]
As with the decision mentioned by Olaf above, this issue becomes obsolete and I will hence close it.
