### ISSUE TITLE
Initial version numbering

### ISSUE THREAD

**Issue by rcapshaw** [LiUGraphQL/woo.sh#65]
As part of the overall build process, I need to begin versioning/tagging this repository. While this ticket is mostly just to document that we are now doing this, I do have two questions.

First, it was suggested to make the initial tag `0.0.1`. When reading through [the page on semantic versioning](https://semver.org/) which GitHub recommends, it is actually suggested to use `v0.1.0` in this case. Note the addition of 'v' and the fact that the minor version is now 1. Do we want to follow this standard?

Second, do we want to include release notes as we do for the mediator service or just leave the version as a lightweight tag?

The tag will be applied to this commit: https://github.com/LiUGraphQL/woo.sh/commit/2ebf233f50988ebf687b2a8f0e2af580f8fe3db2

@hartig @keski

**Comment by hartig** [comment]
Riley, good questions.

Regarding the versioning, I am fine with following that standard; i.e., we start with v0.1.0 (including the 'v' in front of it).

Regarding the release notes, yes, it would be good to create such records right from the start. For this purpose, I have added a CHANGELOG.md file into the root folder of our repo.

@keski @epii-1 this means that, whenever you merge (or push) something to master, do not forget to add a bullet point into that CHANGELOG.md file. For inspiration of how such bullet points should look like, take a look at the release notes of the SPIRIT mediator service: https://gitlab.com/spirit-tools/mediator-service/-/wikis/Release-Notes

Riley, regarding tags, I am not sure whether creating a tag is actual the correct way of creating a release in github. I see that github has a specific release feature: https://github.com/LiUGraphQL/woo.sh/releases

**Comment by rcapshaw** [comment]
The release has been created for the specified commit. Closing this issue since we've also started to collect the changelog in a file, so everything should be addressed.
