### ISSUE TITLE
bug: missing default values for arguments for field

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/woo.sh#71]
The [print_schema_with_directives](https://github.com/LiUGraphQL/woo.sh/blob/master/graphql-api-generator/utils/utils.py) does not print the default values for field arguments. E.g. expected output:
```graphql
listOfX(first: Int=10, after: ID="", filter: _FilterForX): _ListOfX
```
but the function produces:
```graphql
listOfX(first: Int, after: ID, filter: _FilterForX): _ListOfX
```

**Comment by epii-1** [comment]
Should be fixed with #72 now
