### ISSUE TITLE
Empty brackets are not supported by the GraphQL Library

### ISSUE THREAD

**Issue by rcapshaw** [LiUGraphQL/woo.sh#73]
When preparing build 1.7.0, I ran into an issue with the updated schema. In particular, the Job-related changes which introduce types without fields cause the generation of the API schema to fail. It looks like the library we use to parse the schemas doesn't like the use of empty curly brackets "{}". Here's what I've found.

When running woo.sh as suggested with the following command:
```
woo.sh/woo.sh --input graphql-schema/ \
              --output mediator-service/graphql-server \
              --config mediator-service/resources/spirit-api-config.yml \
              --driver arangodb \
              --custom-api-schema mediator-service/resources/spirit-custom-api-schema.graphql \
              --custom-resolvers mediator-service/resources/spirit-custom-resolvers.js
```
I get the following error:
```
Traceback (most recent call last):
  File "generator.py", line 287, in <module>
    cmd(parser.parse_args())
  File "generator.py", line 38, in cmd
    schema = build_schema(schema_string)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/utilities/build_ast_schema.py", line 444, in build_schema
    experimental_fragment_variables=experimental_fragment_variables,
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 104, in parse
    return parse_document(lexer)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 158, in parse_document
    definitions=many_nodes(lexer, TokenKind.SOF, parse_definition, TokenKind.EOF),
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 1166, in many_nodes
    append(parse_fn(lexer))
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 172, in parse_definition
    return parse_type_system_definition(lexer)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 555, in parse_type_system_definition
    return func(lexer)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 747, in parse_interface_type_definition
    fields = parse_fields_definition(lexer)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 679, in parse_fields_definition
    if peek(lexer, TokenKind.BRACE_L)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 1163, in many_nodes
    nodes = [parse_fn(lexer)]
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 688, in parse_field_definition
    name = parse_name(lexer)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 147, in parse_name
    token = expect_token(lexer, TokenKind.NAME)
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 1077, in expect_token
    lexer.source, token.start, f"Expected {kind.value}, found {token.kind.value}"
graphql.error.syntax_error.GraphQLSyntaxError: Syntax Error: Expected Name, found }

GraphQL request:947:16
946 | """
947 | interface Job {
    |                ^
948 | }
```
So, my first thought was to remove empty brackets from the schema (replacing the schema line mentioned above with just `interface Job`, among others). This seemed to work until the pipeline generated the input types, where it threw the same error:
```
Traceback (most recent call last):
  File "generator.py", line 287, in <module>
    cmd(parser.parse_args())
...
  File "/home/riley/anaconda3/envs/spirit/lib/python3.6/site-packages/graphql/language/parser.py", line 1077, in expect_token
    lexer.source, token.start, f"Expected {kind.value}, found {token.kind.value}"
graphql.error.syntax_error.GraphQLSyntaxError: Syntax Error: Expected Name, found }

GraphQL request:186:40
185 | 
186 | extend input _InputToCreateScraperJob {
    |                                        ^
187 | }
```

@hartig @keski @epii-1 How should we proceed? It seems like simply editing the schema files is not enough (else I would have put this ticket elsewhere). Instead, we may need to strip away empty brackets from types with no fields and not generate input types with empty brackets.

**Comment by hartig** [comment]
I don't have a proposal yet for how to proceed, but just some more information related to the issue:

With respect to empty interfaces, I found the following comment: https://github.com/graphql/graphql-js/issues/1517#issuecomment-419916115  Hence, we can**not** have an empty interface :-(

Similarly, [Section 3.10 of the GraphQL spec](http://spec.graphql.org/June2018/#sec-Input-Objects) says that:

> An Input Object type must define one or more input fields.

So, we need to find a way to deal with this problem on the level of our SPIRIT DB schema.

**Comment by epii-1** [comment]
Empty interfaces in the db-schema should not really be an issue (if they are corrected to not have empty {} ). To avoid empty input types for interfaces, we could always add dummy fields that are never used, or required. It might be a "hacky" solution, but it removes the issue from the db-schema level. After all, empty interfaces (and corresponding inputs) makes sense for us as we add fields which can not be used in inputs, but which are there for all object types and interfaces.

**Comment by hartig** [comment]
Regarding Leif's comments:

> Empty interfaces in the db-schema should not really be an issue (if they are corrected to not have empty {} ).  [...]  After all, empty interfaces (and corresponding inputs) makes sense for us as we add fields which can not be used in inputs, but which are there for all object types and interfaces.

I agree. I have modified the definition of the `Job` interface to remove the curly braces.

> To avoid empty input types for interfaces, we could always add dummy fields that are never used, or required. It might be a "hacky" solution, but it removes the issue from the db-schema level.

In general, I agree with this comment too. However, the issue are not "empty input types for interfaces" but empty input types for empty object type (that implement empty interfaces). For instance, we have empty object types `ScraperJob` and `NLPJob`. The question is whether the parser complains about these even if we remove the curly braces there as well?  @rcapshaw an you please check.

If the parser is not complaining, we can simply remove the curly braces from these empty object types and, then, add some dummy non-mandatory field into the corresponding input types when generating these input types.

**Comment by hartig** [comment]
As decided in our telco, Riley will check whether adding a non-mandatory `dummy` field to the (empty) input types causes an issue further down the line. Our assumption is that it does not.

**Comment by rcapshaw** [comment]
Here are my preliminary results:

It is certainly possible to add a `_dummy` field to only those types and input types which do not have any visible fields. When doing so, it generated a schema which, for some reason, did not actually include the dummy field, which was nice enough:
```
type NLPJob implements Job {
  id: ID!
  _jobFromJobExecution(filter: _FilterForJobExecution): [JobExecution]
  _nlpJobFromAnalysis(filter: _FilterForAnalysis): [Analysis] @required
  _creationDate: DateTime!
  _lastUpdateDate: DateTime
}
```
So I figured I would give it a try anyway to see if it would be possible to create a new NLPJob without any input fields. I can submit the query via the playground, but I get an error:
```
mutation {
  createNLPJob
}
```
yields
```
  "error": {
    "errors": [
      {
        "message": "Field \"createNLPJob\" of type \"NLPJob\" must have a selection of subfields. Did you mean \"createNLPJob { ... }\"?",
...
```
And adding in an empty body prevents me from submitting the query.

**Comment by rcapshaw** [comment]
Nevermind me, I just forgot how to use GraphQL. It seems to work with the following query:
```
mutation {
  createNLPJob(data:{}){
    id
  }
}
```
which yields
```
{
  "data": {
    "createNLPJob": {
      "id": "NLPJob/421087"
    }
  }
}
```

**Comment by hartig** [comment]
PR #76 fixes the issue.

**Comment by rcapshaw** [comment]
For now, it looks like we can close this particular issue.
