### ISSUE TITLE
bug: use of keyword INVALID

### ISSUE THREAD

**Issue by keski** [LiUGraphQL/woo.sh#77]
In master, there seems to be an error in [graphql-api-generator/utils/utils.py](https://github.com/LiUGraphQL/woo.sh/blob/master/graphql-api-generator/utils/utils.py). On line 983 there is a reference to a keyword/variable `INVALID` that is not defined, which causes issues during the build process.

```python
if arg.default_value != INVALID:
   # [...]
```

**Comment by epii-1** [comment]
@keski I seem unable to replicate any errors related to this specific line. For me arguments without default values is set to `INVALID` as default and the comparison behaves as expected.
`INVALID` is an actual graphql type and should not cause any issues.
A `type(INVALID)` call gives, and should give `<class 'graphql.error.invalid.InvalidType'>`.
Is there any differences in the version/configuration of the graphql we are using?

**Comment by keski** [comment]
I see, I'll try updating my GraphQL lib and report back.

**Comment by keski** [comment]
It seems that `INVALID` has been deprecated in favor of `Undefined` [graphql-core/issues/77](https://github.com/graphql-python/graphql-core/issues/77). Apparently I had already bumped up my lib to 3.3.1, and `INVALID` is apparently not listed in the modules `__all__` anymore and thus has to be imported explicitly.

**Comment by epii-1** [comment]
As rcapshaw just released the new release. I suggest we update our requirements to be >= 3.1.1 and that I fix this properly for the newer versions then.

**Comment by epii-1** [comment]
I corrected this in de8742a but kept the backwards compatibility with version of grapql-core <3.1.1.
If we want to enforce version 3.1.1, or discuss it, I suggest opening a new issue as I'm closing this one now.
