### ISSUE TITLE
Develop branch gets error during create and update operations

### ISSUE THREAD

**Issue by epii-1** [LiUGraphQL/woo.sh#78]
@keski I'm getting error while running `client-test` with mediators generated from the develop branch:
```
graphQLErrors: [
    {
      message: "ArangoError: AQL: bind parameter 'value2' was not declared in the query (while parsing)",
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
```
The error seem to always be related to `value2`. Is the parameters (other than the first) not getting defined correctly? Or do I have any dependencies out of sync or something?

PS: I have to run `let inputToCreate = tools.makeInputToCreate(t, schema, 4, true);` with 4 or above, else I get another error related to dummy fields?

**Comment by keski** [comment]
I'll have a look at the issue.

For reference, the dummy fields error is related to how the client tests stop generating nested fields for creation at a given depth. At the depth limit it stops creating objects and instead connects to dummy IDs. The option to increasing the depth is to disable edge validation completely on the server side (i.e., where it checks that the vertices for an edge actually exist in the correct collection/interface).

**Comment by keski** [comment]
I was unable to replicate the error. Could you verify that you have the update starwars schema (with required fields for key types) and also drop the DB when you start the server?

**Comment by epii-1** [comment]
I'm using the SPIRIT schema, so that might be that issue.

**Comment by epii-1** [comment]
After some (quite a lot) of testing I finally figured it out: I was still using the old version of `client-test` and `generation-tools`.
Now there is just the issue of the dummy fields...
