### ISSUE TITLE
delete-node operations

### ISSUE THREAD

**Issue by hartig** [LiUGraphQL/woo.sh#82]
woo.sh has to generate the API declarations and the corresponding code for mutation operations to delete existing nodes (including the incident edges!) [as documented in the wiki](https://github.com/LiUGraphQL/woo.sh/wiki/Overview-of-the-Approach#53-deleting-an-object).

Note that the deletion of the incident edges may result in constraint violations. Hence, implementing the relevant constraint checks is part of this issue (which should then tick one of the check boxes in #62).

**Comment by epii-1** [comment]
With #82 merged, this is now implemented.
