### ISSUE TITLE
ArangoDB driver fails on initial startup when DROP=true

### ISSUE THREAD

**Issue by rcapshaw** [LiUGraphQL/woo.sh#89]
Adding a ticket here in reference to https://gitlab.com/spirit-tools/mediator-service/-/issues/84, since the issue is fixed by updating `arangodb\driver.js` to properly perform a check. The check is not the nicest--the only way seemed to be to list all databases and check if the one we expect to drop is in that list. The issue itself did not seem to prevent the construction of the database on initial runs, but having an error logged for the first run is fairly ugly and may in the future cause the whole process to fail.

**Comment by hartig** [comment]
PR #90 closes this issue.
