### ISSUE TITLE
Woo.sh and Unions

### ISSUE THREAD

**Issue by epii-1** [LiUGraphQL/woo.sh#95]
Following Christians issue 72 in spirits graphql-schema. Do we want to support unions? And if so, to what degree?
There are likely some limitations we could put on unions (at least to begin with) to simplify things for ourselves.
Unions of only scalars and enums are likely simpel to handle. Similarly unions of only interfaces and types are likely also simpel. Unions containing both scalars/enums and interfaces/types might become problematic, but still doable .

@hartig @keski @rcapshaw

**Comment by hartig** [comment]
Although we discussed it during our telco in the morning, here's a summary for the record: We should support union types, but:
1. only as a way to specify alternative target types for edge types defined in a DB schema, and
2. only in a spec-conformant manner.

An implication of point 1 is that we don't need to support querying based on union types (i.e., no query operations for union types). Therefore, the only effects that a union type in the DB schema would have on the resulting API schema are: i) the union type must be copied over and ii) the input types for the inline creation of edges together with their target nodes must contain `create` fields for all types that belong to the union type (i.e., in the same way as done for edge types with an interface as target type).

Point 2 means that we do not have to worry about union types that consist of scalar types, of interface types, or of other union types.
